org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2

fabric_version=0.116.14+1.21.1

fabric_kotlin_version=1.13.3+kotlin.2.1.21
mod_version=1.0
maven_group=com.kaizzinho
archives_base_name=cobblemon-battle-introduction
cobblemon_version=1.8.0+1.21.1